### ISSUE TITLE
Unexpected token >

### ISSUE THREAD

**Issue by lewixlabs** [kern/filepizza#20]
Error is related on row 56 of server.js module, after launching filepizza (no extra parameters)

Details:
C:\Users\xxxx\AppData\Roaming\npm\node_modules\filepizza\lib\server.js:56
    db.create(socket).then((u) => {
                                ^
SyntaxError: Unexpected token >

OS: Windows 7 64 bit
Node version: v0.10.26
Npm version: v2.11.3
Python version: 2.7.10

Thank you for any suggestion.

Lewix

**Comment by kern** [comment]
Should be fixed in `0.2.2`. I removed the runtime dependency on Babel, which seemed to be the issue.

**Comment by lewixlabs** [comment]
Hi,
after updating filepizza by npm (i tried to reinstall too) i get this error:
C:\Users\xxxxx>filepizza

module.js:340
    throw err;
          ^
Error: Cannot find module './dist/server'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\xxxx\AppData\Roaming\npm\node_modules\f
ilepizza\index.js:10:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

Maybe during reinstall has something been corrupted?
Thank you for any suggestion.

Lewix

**Comment by lewixlabs** [comment]
Little update:
i tried also on a new virtual machine with Ubuntu (15.04) and after installing nodejs/npm, git and python same issue happened.

Hi,
Lewix

**Comment by kern** [comment]
Try `0.2.3`, should be fixed. Thanks!
