### ISSUE TITLE
Error: Cannot find module './dist/server'

### ISSUE THREAD

**Issue by arminus** [kern/filepizza#21]
Re-Installed with npm install filepizza -g :

```
env PORT=3457 filepizza
module.js:338
    throw err;
          ^
Error: Cannot find module './dist/server'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/filepizza/index.js:10:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

There is no ./dist obviously after the install ...

**Comment by kern** [comment]
Oops, I shouldn't have been ignoring `dist/` when publishing (5741b1aef6f492b9e4367ab47890eec167f7f52e). Fixed in `0.2.3`, thanks!
